### ISSUE TITLE
Update README.md based on the `Debug GazeboROS`group

### ISSUE THREAD

**Issue by ogurcan** [KiloNovemberDelta/IPSANavigation#1]
I propose you to update the README.md file as following:

*. Add `sudo apt-get install python-rosdep` after the command `sudo apt install ros-melodic-desktop-full` for Ubuntu 18.04.
*. Add `sudo chown -R $USER ~/.ros` after the command `roscore & rosrun gazebo_ros gazebo` for Ubuntu 18.04.

These are the commands discussed in the `Debug GazeboROS` group. If you think that there are further improvements to be done, I suggest you to do them. 

Having an up to date README.md will avoid people to lose time.

**Comment by KiloNovemberDelta** [comment]
Good point indeed, I will update the REAMDE.md as you suggested ;)

**Comment by ogurcan** [comment]
Thank you for adding them. However, rather than putting them in a `Debug during installation :` subsection, you can directly put them inside the installation instructions so that when installing, people will not see any error messages at all. 

If `python-rosdep` is already installed, `sudo apt-get install python-rosdep` will not install it again, and if the owner of `~/.ros` is already `$USER`, `sudo chown -R $USER ~/.ros` will not do something wrong. So having them in the installation instructions will not have any side effect.

**Comment by KiloNovemberDelta** [comment]
Changed commited ;)
